# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ariky/Documents/CMPE100/lab7/lab7.cache/wt [current_project]
set_property parent.project_path C:/Users/ariky/Documents/CMPE100/lab7/lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/ariky/Documents/CMPE100/lab7/lab7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/new/chooseRND.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/new/m8x16.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/LFSR.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/countUD4L.v
  {C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/Full Adder.v}
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/m8_1e.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/Downloads/lab7_clks.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/new/Gate_Machine.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/TurkeyCounter.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/sources_1/imports/new/Selector.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/sources_1/imports/new/RingCounter.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/sources_1/new/m2_1x1.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/sources_1/imports/new/hex7seg.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/sources_1/new/AddOne.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/TimeCounter.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/new/StateMachine.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/new/Every8Frame.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/counterUD16L.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/imports/new/m2_1x8.v
  C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/sources_1/new/VGAcontrol.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/constrs_1/imports/Lab2/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/ariky/Documents/CMPE100/lab7/lab7.srcs/constrs_1/imports/Lab2/Basys3_Master.xdc]


synth_design -top VGAcontrol -part xc7a35tcpg236-1


write_checkpoint -force -noxdef VGAcontrol.dcp

catch { report_utilization -file VGAcontrol_utilization_synth.rpt -pb VGAcontrol_utilization_synth.pb }
